################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TODISASSEMBLE_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
O_SRCS_QUOTED := 
LD_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
O_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
TOPREPROCESS_SRCS_OS_FORMAT := 
O_SRCS := 
ELF_SRCS := 
TOPREPROCESS_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_SRCS_QUOTED := 
S_SRCS_QUOTED := 
ELF_SRCS_QUOTED := 
ELF_SRCS_OS_FORMAT := 
ASM_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
ASM_SRCS := 
S_UPPER_SRCS_OS_FORMAT := 
S_UPPER_SRCS := 
ASM_SRCS_QUOTED := 
OBJ_SRCS_QUOTED := 
LD_SRCS := 
LD_SRCS_QUOTED := 
OBJ_SRCS := 
S_SRCS := 
TOPREPROCESS_SRCS := 
C_SRCS := 
ASM_UPPER_SRCS_OS_FORMAT := 
SECONDARY_FLASH_QUOTED := 
SECONDARY_SIZE_OS_FORMAT := 
C_DEPS_QUOTED := 
SECONDARY_LIST := 
SECONDARY_SIZE := 
SECONDARY_LIST_OS_FORMAT := 
OBJS_QUOTED := 
SECONDARY_LIST_QUOTED := 
C_DEPS := 
C_DEPS_OS_FORMAT := 
OBJS_OS_FORMAT := 
EXECUTABLES_OS_FORMAT := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_FLASH_OS_FORMAT := 
SECONDARY_SIZE_QUOTED := 
EXECUTABLES_QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources/mid/wdg \
Sources/mid/timer \
Sources/mid/srs \
Sources/mid/softrtc \
Sources/mid/rtc \
Sources/mid/power_mode_switch \
Sources/mid/pm \
Sources/mid/pin \
Sources/mid/msg \
Sources/mid/kernel \
Sources/mid/ipc_spi \
Sources/mid/i2c \
Sources/mid/gpio \
Sources/mid/flash \
Sources/mid/edma \
Sources/mid/dbg_uart \
Sources/mid/dbg_trace \
Sources/mid/config \
Sources/mid/clock \
Sources/mid/can_spi \
Sources/mid/can_flexcan \
Sources/mid/call \
Sources/mid/brdinfo \
Sources/mid/aes \
Sources/mid/adc \
Sources/mid/acc \
Sources \
Sources/app/tp/uds \
Sources/app/tp/proxy \
Sources/app/shell \
Sources/app/scom \
Sources/app/power \
Sources/app/nm_osek \
Sources/app/nm_autosar \
Sources/app/mcu_mgr \
Sources/app/custom \
Sources/app/can_mgr \
Sources/app/battery \
SDK/rtos/osif \
SDK/platform/hal/src/wdog \
SDK/platform/hal/src/smc \
SDK/platform/hal/src/sim/S32K144 \
SDK/platform/hal/src/scg \
SDK/platform/hal/src/rtc \
SDK/platform/hal/src/rcm \
SDK/platform/hal/src/port \
SDK/platform/hal/src/pmc \
SDK/platform/hal/src/pcc \
SDK/platform/hal/src/lpuart \
SDK/platform/hal/src/lpspi \
SDK/platform/hal/src/lpi2c \
SDK/platform/hal/src/ftm \
SDK/platform/hal/src/flexcan \
SDK/platform/hal/src/edma \
SDK/platform/hal/src/dmamux \
SDK/platform/hal/src/adc \
SDK/platform/drivers/src/wdog \
SDK/platform/drivers/src/rtc \
SDK/platform/drivers/src/power \
SDK/platform/drivers/src/pins \
SDK/platform/drivers/src/lpuart \
SDK/platform/drivers/src/lpspi \
SDK/platform/drivers/src/lpi2c \
SDK/platform/drivers/src/interrupt \
SDK/platform/drivers/src/ftm \
SDK/platform/drivers/src/flexcan \
SDK/platform/drivers/src/flash \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/clock \
SDK/platform/drivers/src/clock/S32K144 \
SDK/platform/drivers/src/adc \
SDK/platform/devices \
SDK/platform/devices/S32K144/startup \
Project_Settings/Startup_Code \
Generated_Code \

